In [1]:
from numpy import array

In [2]:
from numpy import mean

In [3]:
from numpy import cov

In [4]:
from numpy.linalg import eig

In [5]:
import pandas as pd

In [6]:
#define a mateix

In [7]:
P = array([[1.2, 2.4],
          [0.5, 1.8],
          [2, 4.5],
          [2.8, 3.1],
          [1.1, 2.4],
          [5, 1.7],
          [2.1, 3.2],
          [3, 5.1],
          [4.7, 3.4],
          [2.3, 3.1]])

In [8]:
print(P)

[[1.2 2.4]
 [0.5 1.8]
 [2.  4.5]
 [2.8 3.1]
 [1.1 2.4]
 [5.  1.7]
 [2.1 3.2]
 [3.  5.1]
 [4.7 3.4]
 [2.3 3.1]]


In [9]:
#mean

In [10]:
M =mean(P.T,axis=1)

In [11]:
print (M)

[2.47 3.07]


In [12]:
C = P - M

In [13]:
print(C)

[[-1.27 -0.67]
 [-1.97 -1.27]
 [-0.47  1.43]
 [ 0.33  0.03]
 [-1.37 -0.67]
 [ 2.53 -1.37]
 [-0.37  0.13]
 [ 0.53  2.03]
 [ 2.23  0.33]
 [-0.17  0.03]]


In [14]:
#Calculate covariance matrix

In [15]:
V = cov(C.T)

In [16]:
print(V)

[[2.169      0.21122222]
 [0.21122222 1.18677778]]


In [17]:
#Eigen decomposition of covariance matrix

In [18]:
values, vectors = eig(V)

In [19]:
print(values)

[2.21249618 1.1432816 ]


In [20]:
print(vectors)

[[ 0.97944857 -0.20169406]
 [ 0.20169406  0.97944857]]


In [21]:
K = vectors.T.dot(C.T)

In [22]:
print(K.T)

[[-1.37903471 -0.40007909]
 [-2.18566514 -0.8465624 ]
 [-0.17191833  1.49540767]
 [ 0.32926885 -0.03717558]
 [-1.47697956 -0.37990969]
 [ 2.20168403 -1.85213051]
 [-0.33617574  0.20195512]
 [ 0.92854668  1.88138275]
 [ 2.25072936 -0.12655972]
 [-0.16045544  0.06367145]]


In [23]:
from sklearn.decomposition import PCA

In [24]:
pca = PCA(2)

In [25]:
pca.fit_transform(P)

array([[-1.37903471, -0.40007909],
       [-2.18566514, -0.8465624 ],
       [-0.17191833,  1.49540767],
       [ 0.32926885, -0.03717558],
       [-1.47697956, -0.37990969],
       [ 2.20168403, -1.85213051],
       [-0.33617574,  0.20195512],
       [ 0.92854668,  1.88138275],
       [ 2.25072936, -0.12655972],
       [-0.16045544,  0.06367145]])

In [26]:
print(pca.components_)

[[ 0.97944857  0.20169406]
 [-0.20169406  0.97944857]]


In [27]:
print(pca.explained_variance_)

[2.21249618 1.1432816 ]


In [28]:
B= pca.transform(P)

In [29]:
print(B)

[[-1.37903471 -0.40007909]
 [-2.18566514 -0.8465624 ]
 [-0.17191833  1.49540767]
 [ 0.32926885 -0.03717558]
 [-1.47697956 -0.37990969]
 [ 2.20168403 -1.85213051]
 [-0.33617574  0.20195512]
 [ 0.92854668  1.88138275]
 [ 2.25072936 -0.12655972]
 [-0.16045544  0.06367145]]
