In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import statsmodels.api as sm

In [4]:
import seaborn as sns

In [5]:
import matplotlib.pyplot as plt

In [6]:
import math

In [7]:
df = pd.read_csv('amsPrediction.csv')

In [8]:
df.head()

Attendance  MSE  HRS  ESE
0          70   10   17   42
1          92    7   20   39
2          67    3   18   32
3          82   16   13   50
4          80    9   10   44

In [9]:
df.describe()

Attendance        MSE        HRS        ESE
count   73.000000  73.000000  73.000000  73.000000
mean    81.698630   9.780822  12.904110  46.630137
std      9.506847   3.047069   5.701278   6.617542
min     62.000000   3.000000   2.000000  32.000000
25%     75.000000   8.000000   8.000000  42.000000
50%     80.000000  10.000000  14.000000  47.000000
75%     90.000000  11.000000  18.000000  50.000000
max     98.000000  17.000000  22.000000  64.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Attendance  73 non-null     int64
 1   MSE         73 non-null     int64
 2   HRS         73 non-null     int64
 3   ESE         73 non-null     int64
dtypes: int64(4)
memory usage: 2.4 KB


In [11]:
endog = df['ESE'].head()

In [12]:
exog = df[['MSE','Attendance','HRS']].head()

In [13]:
print(exog)

   MSE  Attendance  HRS
0   10          70   17
1    7          92   20
2    3          67   18
3   16          82   13
4    9          80   10


In [14]:
X = exog.to_numpy()
Y = endog.to_numpy()

In [15]:
print (X)

[[10 70 17]
 [ 7 92 20]
 [ 3 67 18]
 [16 82 13]
 [ 9 80 10]]


In [16]:
from numpy import array

In [17]:
from numpy import mean

In [18]:
from numpy import cov

In [19]:
from numpy.linalg import eig

In [20]:
M = mean(X.T, axis=1)

In [21]:
print(M)

[ 9.  78.2 15.6]


In [22]:
C = X -M

In [23]:
print(C)

[[  1.   -8.2   1.4]
 [ -2.   13.8   4.4]
 [ -6.  -11.2   2.4]
 [  7.    3.8  -2.6]
 [  0.    1.8  -5.6]]


In [24]:
#covariance matrix

In [25]:
V = cov(C.T)

In [26]:
print(V)

[[ 22.5  14.5 -10. ]
 [ 14.5 100.2   0.6]
 [-10.    0.6  16.3]]


In [27]:
#Eigen decomposition of covariance matrix

In [28]:
values, vectors = eig(V)

In [29]:
print(values)

[102.83421474  28.19086641   7.97491885]


In [30]:
print(vectors)

[[-0.1792837  -0.75344094  0.63260107]
 [-0.98369925  0.14637427 -0.10445268]
 [ 0.01389759  0.64101586  0.7674018 ]]


In [31]:
P = vectors.T.dot(C.T)

In [32]:
print(P.T)

[[  7.90650678  -1.05628772   2.56347554]
 [-13.15533283   6.34731651   0.66991886]
 [ 12.126488     4.4196919   -0.7839721 ]
 [ -5.02917677  -6.38450557   2.03604261]
 [ -1.84848518  -3.32621512  -4.48546492]]


In [33]:
from sklearn.decomposition import PCA

In [34]:
pca = PCA(n_components=1)

In [35]:
principalComponents = pca.fit_transform(X)

In [36]:
principalDF = pd.DataFrame(data = principalComponents, columns = ['principal component 1'])

In [37]:
exog1 = sm.add_constant(principalDF[['principal component 1']])

In [38]:
print(exog1)

   const  principal component 1
0    1.0              -7.906507
1    1.0              13.155333
2    1.0             -12.126488
3    1.0               5.029177
4    1.0               1.848485


In [39]:
from sklearn import linear_model

In [40]:
lm = linear_model.LinearRegression()

In [41]:
model = lm.fit(exog1, endog)

In [42]:
lm.coef_

array([0.       , 0.3056601])

In [43]:
lm.intercept_

41.4

In [44]:
def RSE (y_true, y_predicted):
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse= math.sqrt(RSS / (len(y_true)-2))
    return rse

In [45]:
ypre = lm.predict(exog1)

In [46]:
re = RSE(endog, ypre)

In [47]:
print(re)

6.752026356402881
